apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: oci://registry-1.docker.io/k8s-dashboard
      name: k8s-dashboard
      type: helm
      enableOCI: "true"
      insecure: "true"